database:
  driverClass: org.sqlite.JDBC
  url: "jdbc:sqlite:/data/workouts.db"

server:
  rootPath: /api/
  applicationConnectors:
  - type: http
    port: 80

logging:
  level: INFO
  loggers:
    com.weizilla.workouts: DEBUG
