version: "3"
services:
  workouts:
    image: weizilla/workouts:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - GARMIN_USERNAME
      - GARMIN_PASSWORD
