version: "2"
services:
  workouts:
    image: weizilla/workouts:latest
    mem_limit: 256m
    ports:
      - "80:8080"
    volumes:
      - /data:/data
    environment:
      - GARMIN_USERNAME
      - GARMIN_PASSWORD

